name: Schedule Bot Startup

on:
  schedule:
    # Her gün 09:00 UTC'de çalışır (Türkiye saatiyle sabah 12:00)
    - cron: '0 9 * * *'
  workflow_dispatch: # Manuel çalıştırma için

jobs:
  resume-and-redeploy-service: # Job adını güncelleyelim
    runs-on: ubuntu-latest
    steps:
      - name: Resume Render Service # 1. Adım: Servisi devam ettir
        id: resume
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "Attempting to resume service..."
          curl -v --request POST \
            --url https://api.render.com/v1/services/${RENDER_SERVICE_ID}/resume \
            --header 'Accept: application/json' \
            --header "Authorization: Bearer ${RENDER_API_KEY}" \
            --fail

      - name: Wait for service to potentially stabilize # 2. Adım: Kısa bir süre bekle
        if: steps.resume.outcome == 'success'
        run: sleep 15 # 15 saniye bekle

      - name: Trigger Redeploy Render Service # 3. Adım: Yeniden Deploy'u tetikle
        if: steps.resume.outcome == 'success'
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "Attempting to trigger redeploy..."
          curl -v --request POST \
            --url https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys \ # <--- URL /deploys olarak değişti
            --header 'Accept: application/json' \
            --header "Authorization: Bearer ${RENDER_API_KEY}" \
            --data '{}' # <--- Genellikle boş bir JSON veya hiç data gönderilmez, boş JSON daha güvenli olabilir
            --fail