name: Schedule Bot Shutdown

on:
  schedule:
    # Her gün 22:00 UTC'de çalışır (Polonya saatiyle gece 00:00)
    - cron: '0 22 * * *'
  workflow_dispatch: # Manuel çalıştırma için

jobs:
  scale-down:
    runs-on: ubuntu-latest
    steps:
      - name: Scale Render Service to 0 Instances
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl --request PATCH \
            --url https://api.render.com/v1/services/${RENDER_SERVICE_ID} \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --header "Authorization: Bearer ${RENDER_API_KEY}" \
            --data '{"numInstances": 0}'