name: Schedule Bot Startup

on:
  schedule:
    - cron: '0 8 * * *' # Sabah 11:00 TRT
  workflow_dispatch:

jobs:
  resume-service: # Job adını değiştirmek isteyebilirsin
    runs-on: ubuntu-latest
    steps:
      - name: Resume Render Service
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl --request POST \ # <--- POST olarak değiştirildi
            --url https://api.render.com/v1/services/${RENDER_SERVICE_ID}/resume \ # <--- URL /resume olarak değiştirildi
            --header 'Accept: application/json' \
            --header "Authorization: Bearer ${RENDER_API_KEY}"
          # --data kısmı kaldırıldı