name: Schedule Bot Shutdown

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  suspend-service: # Job adını değiştirmek isteyebilirsin
    runs-on: ubuntu-latest
    steps:
      - name: Suspend Render Service
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl --request POST \ # <--- POST olarak değiştirildi
            --url https://api.render.com/v1/services/${RENDER_SERVICE_ID}/suspend \ # <--- URL /suspend olarak değiştirildi
            --header 'Accept: application/json' \
            --header "Authorization: Bearer ${RENDER_API_KEY}"
          # --data kısmı kaldırıldı