name: Schedule Bot Startup

on:
  schedule:
    # Her gün 09:00 UTC'de çalışır (Türkiye saatiyle sabah 12:00)
    - cron: '0 9 * * *'
  workflow_dispatch: # Manuel çalıştırma için

jobs:
  resume-service: # Job adı isteğe bağlı olarak değiştirilebilir
    runs-on: ubuntu-latest
    steps:
      - name: Resume Render Service
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |  # Pipe karakterinden sonraki satırda hemen komut başlamalı
          curl --request POST \
            --url https://api.render.com/v1/services/${RENDER_SERVICE_ID}/resume \
            --header 'Accept: application/json' \
            --header "Authorization: Bearer ${RENDER_API_KEY}"